name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python 3.6 throws an error:
        # https://stackoverflow.com/q/69174965/709975
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8
      - name: Install dependencies
        run: |
          pip install ".[dev]"
      - name: Unit tests
        run: |
          pytest --ignore=tests/test_sample_notebooks.py
      - name: Install integration tests dependencies
        run: |
          pip install -r _kaggle/requirements.txt
      - name: Integration tests
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          PLOOMBER_STATS_ENABLED: false
        run: |
          pytest tests/test_sample_notebooks.py